
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: localpro-app
    container_name: localpro-app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - localpro
    environment:
      - NODE_ENV=production
    command: >
      sh -c "
        echo 'Building LocalPro...';
        npm install &&
        npm run build &&
        npm run start
      "
    ports:
      - "3001:3001"

  webserver:
    image: nginx:alpine
    container_name: localpro-webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
      - ./docker/nginx/public.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - localpro

networks:
  localpro:
    driver: bridge
